apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app2
  namespace: default
spec:
  interval: 10m
  path: "./kubernetes/App2/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app2
